### ISSUE TITLE
Hi ，Why I can only download 6 minutes of video after I have added a cookie

### ISSUE THREAD

**Issue by ali617768987** [sohail0098/iqiyi-dl#1]
First of all, thank you for providing a new download tool to download IQIYI videos. I tried it today and found that I have added cookies but can only download 6-minute videos. Is there a problem with my operation? Can you help me?

i found the vip episode just can download 6-min
![微信截图_20210722101106](https://user-images.githubusercontent.com/77323405/126582022-272f4047-1fb5-4511-8b7b-c7f3235dba40.png)
![微信截图_20210722101156](https://user-images.githubusercontent.com/77323405/126582033-81e41075-096e-4b7d-a7ae-518e6e0cd93d.png)
![微信截图_20210722101255](https://user-images.githubusercontent.com/77323405/126582037-4a244909-546f-4dd3-bb05-30962ca7d430.png)

**Comment by sohail0098** [comment]
Hi. I am really sorry for not mentioning information about cookies in the README file. The cookie is a bit different in this situation. 
To get the cookie, click on the dash link in the network tab, and scroll down a bit on the headers tab to find the 'cookie' under the request headers section. 
![image](https://user-images.githubusercontent.com/24472929/126594285-b7825ebb-8507-4188-8154-0cae52737a46.png)
I will try to see if I can change the cookie section to be able to use cookies that are copied from storage or through extension.

Alternatively, you can press 'm' to use a pre-set cookie which is valid for a few weeks from now. 

Please let me know if this works. In this case, it should have worked even if you did not add a cookie. The cookie is needed on iqiyi for downloading the `unlocked` episodes for an account. I'll need to look into this a bit to confirm if this is due to any recent changes.

**Comment by ali617768987** [comment]
Thanks a lot，it can works ~

**Comment by ali617768987** [comment]
> Hi. I am really sorry for not mentioning information about cookies in the README file. The cookie is a bit different in this situation.
> To get the cookie, click on the dash link in the network tab, and scroll down a bit on the headers tab to find the 'cookie' under the request headers section.
> ![image](https://user-images.githubusercontent.com/24472929/126594285-b7825ebb-8507-4188-8154-0cae52737a46.png)
> I will try to see if I can change the cookie section to be able to use cookies that are copied from storage or through extension.
> 
> Alternatively, you can press 'm' to use a pre-set cookie which is valid for a few weeks from now.
> 
> Please let me know if this works. In this case, it should have worked even if you did not add a cookie. The cookie is needed on iqiyi for downloading the `unlocked` episodes for an account. I'll need to look into this a bit to confirm if this is due to any recent changes.

Thanks a lot，it can works ~
