### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by Sparh4wk** [sohail0098/iqiyi-dl#3]
Hi,

thanks for amazing tool. Just wondering, is there a easy way to change the code so it will download only english subtitles?
Cause for some reason it makes all subtitles as default language and choose one of them randomly :(

Thanks

**Comment by sohail0098** [comment]
Hi there. 
Yes, I am aware about all the subtitle tracks being set to default but since most of the people around here were using media players with configs for default language tracks, I never bothered to make the commit to fix it. 
Anyway, removing stuff is pretty easy but I would like to give you a better, short and convenient option. 

Make the following change and all other subtitles apart from English will no longer bet marked as default. 
https://github.com/sohail0098/iqiyi-dl/blob/main/iqiyi-dl.py#L78
At line 78, add `--default-track 0:no ` in the single quote section (there's a space as well)
![Here's an image for reference if needed](https://prnt.sc/1z8sdzt)

**Comment by Sparh4wk** [comment]
thanks!
